import { GoogleGenAI } from "@google/genai";

export interface ImageGenerationResult {
  imageUrl: string;
  revisedPrompt?: string;
}

export async function generateGeminiImage(prompt: string): Promise<ImageGenerationResult> {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("VITE_GEMINI_API_KEY is not configured in environment variables.");
  }

  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    let imageUrl = '';
    let revisedPrompt = '';

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        const base64EncodeString = part.inlineData.data;
        imageUrl = `data:image/png;base64,${base64EncodeString}`;
      } else if (part.text) {
        revisedPrompt = part.text;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return { imageUrl, revisedPrompt };
  } catch (error) {
    console.error("Gemini Image Generation Error:", error);
    if (error instanceof Error) {
      throw error;
    }
    throw new Error("Failed to generate image with Gemini.");
  }
}
